"""
Test Suite for NeuralShield-AI Output Integrity Watermarker
June 2026 Production Release

Comprehensive tests for watermarking and tamper detection functionality.
"""
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'neural_shield'))

from output_integrity_watermarker_provenance_2026_june import (
    OutputIntegrityWatermarker,
    WatermarkType,
    TamperVerdict,
    WatermarkMetadata
)

def test_basic_watermarking():
    """Test basic watermark embedding and verification"""
    print("Test 1: Basic Watermarking")
    print("-" * 50)
    
    watermarker = OutputIntegrityWatermarker(secret_key="test-secret-key-2026")
    
    original_text = """
    Artificial intelligence (AI) is intelligence demonstrated by machines,
    as opposed to natural intelligence displayed by animals including humans.
    AI research has been defined as the field of study of intelligent agents,
    which refers to any system that perceives its environment and takes actions
    that maximize its chance of achieving its goals.
    """
    
    # Apply watermark
    result = watermarker.watermark_output(
        text=original_text,
        model_name="gpt-4",
        conversation_id="conv-12345-abcde",
        turn_number=1,
        prompt_text="Explain artificial intelligence"
    )
    
    print(f"Original length: {len(original_text)}")
    print(f"Watermarked length: {len(result.watermarked_text)}")
    print(f"Watermark added: {result.watermark_length} chars")
    print(f"Watermark type: {result.watermark_type.value}")
    print(f"Model: {result.metadata.model_name}")
    print(f"Output hash: {result.metadata.output_hash[:16]}...")
    
    # Verify
    verification = watermarker.verify_watermark(result.watermarked_text)
    
    print(f"\nVerification:")
    print(f"  Valid: {verification.is_valid}")
    print(f"  Verdict: {verification.verdict.value}")
    print(f"  Confidence: {verification.confidence:.1%}")
    print(f"  Integrity Score: {verification.integrity_score:.1%}")
    
    assert verification.verdict in [TamperVerdict.UNMODIFIED, TamperVerdict.MINOR_TAMPERING]
    print("✓ PASSED\n")
    return True

def test_tamper_detection():
    """Test tampering detection functionality"""
    print("Test 2: Tamper Detection")
    print("-" * 50)
    
    watermarker = OutputIntegrityWatermarker(secret_key="test-secret-key-2026")
    
    original_text = "The quick brown fox jumps over the lazy dog. This is a test message for watermark verification."
    
    # Apply watermark
    result = watermarker.watermark_output(
        text=original_text,
        model_name="claude-3",
        conversation_id="conv-tamper-test",
        turn_number=1
    )
    
    # Create tampered version
    tampered_text = result.watermarked_text.replace("lazy dog", "ACTIVE THREAT")
    
    # Verify original
    orig_verification = watermarker.verify_watermark(result.watermarked_text)
    print(f"Original - Verdict: {orig_verification.verdict.value}, Score: {orig_verification.integrity_score:.1%}")
    
    # Verify tampered
    tamper_verification = watermarker.verify_watermark(tampered_text)
    print(f"Tampered  - Verdict: {tamper_verification.verdict.value}, Score: {tamper_verification.integrity_score:.1%}")
    
    # Integrity score should be lower for tampered
    assert tamper_verification.integrity_score < orig_verification.integrity_score
    print("✓ PASSED - Tampering correctly detected\n")
    return True

def test_hash_watermark_type():
    """Test hash embedded watermark type"""
    print("Test 3: Hash Embedded Watermark Type")
    print("-" * 50)
    
    watermarker = OutputIntegrityWatermarker(
        secret_key="test-secret-key-2026",
        watermark_type=WatermarkType.HASH_EMBEDDED
    )
    
    text = "This is confidential AI-generated content that requires integrity verification."
    
    result = watermarker.watermark_output(
        text=text,
        model_name="llama-3",
        conversation_id="conv-hash-test",
        turn_number=1
    )
    
    print(f"Watermark type: {result.watermark_type.value}")
    print(f"Watermarked text ends with: ...{result.watermarked_text[-50:]}")
    
    verification = watermarker.verify_watermark(result.watermarked_text)
    print(f"Verification verdict: {verification.verdict.value}")
    print(f"Integrity score: {verification.integrity_score:.1%}")
    
    print("✓ PASSED\n")
    return True

def test_cryptosign_watermark():
    """Test full cryptographic signature watermark"""
    print("Test 4: Full Cryptographic Signature Watermark")
    print("-" * 50)
    
    watermarker = OutputIntegrityWatermarker(
        secret_key="production-key-2026-june",
        watermark_type=WatermarkType.FULL_CRYPTOSIGN
    )
    
    text = "Sensitive financial report generated by AI. This document requires full provenance tracking."
    
    result = watermarker.watermark_output(
        text=text,
        model_name="gpt-4o",
        conversation_id="finance-report-001",
        turn_number=1,
        prompt_text="Generate Q2 financial summary"
    )
    
    print(f"Watermark type: {result.watermark_type.value}")
    print(f"Verification key: {result.verification_key[:24]}...")
    
    # Check signature block exists
    assert "NeuralShield Integrity Signature" in result.watermarked_text
    
    # Generate report
    verification = watermarker.verify_watermark(result.watermarked_text)
    report = watermarker.get_provenance_report(verification)
    print("\nProvenance Report:")
    print(report[:300] + "...")
    
    print("✓ PASSED\n")
    return True

def test_no_watermark_detection():
    """Test detection of text without watermarks"""
    print("Test 5: No Watermark Detection")
    print("-" * 50)
    
    watermarker = OutputIntegrityWatermarker()
    
    unwatermarked_text = "This is plain text without any watermark."
    
    verification = watermarker.verify_watermark(unwatermarked_text)
    
    print(f"Text: {unwatermarked_text}")
    print(f"Verdict: {verification.verdict.value}")
    print(f"Confidence: {verification.confidence:.1%}")
    
    assert verification.verdict == TamperVerdict.NO_WATERMARK
    print("✓ PASSED\n")
    return True

def test_hash_similarity_calculation():
    """Test hash similarity calculation"""
    print("Test 6: Hash Similarity Calculation")
    print("-" * 50)
    
    watermarker = OutputIntegrityWatermarker()
    
    # Test identical hashes
    similarity = watermarker._calculate_hash_similarity("abcdef123456", "abcdef123456")
    print(f"Identical hashes similarity: {similarity:.1%}")
    assert similarity == 1.0
    
    # Test different hashes
    similarity = watermarker._calculate_hash_similarity("abcdef123456", "000000000000")
    print(f"Different hashes similarity: {similarity:.1%}")
    assert similarity < 0.5
    
    print("✓ PASSED\n")
    return True

def run_all_tests():
    """Run all test cases"""
    print("=" * 60)
    print("NeuralShield-AI Output Integrity Watermarker - Test Suite")
    print("June 2026 Production Release")
    print("=" * 60 + "\n")
    
    tests = [
        test_basic_watermarking,
        test_tamper_detection,
        test_hash_watermark_type,
        test_cryptosign_watermark,
        test_no_watermark_detection,
        test_hash_similarity_calculation,
    ]
    
    passed = 0
    failed = 0
    
    for test in tests:
        try:
            if test():
                passed += 1
        except Exception as e:
            print(f"✗ FAILED: {e}")
            failed += 1
    
    print("=" * 60)
    print(f"Results: {passed} PASSED, {failed} FAILED")
    print(f"Success rate: {passed/(passed+failed):.1%}")
    print("=" * 60)
    
    return failed == 0

if __name__ == "__main__":
    success = run_all_tests()
    sys.exit(0 if success else 1)
