"""
NeuralShield-AI: Threat Intelligence MITRE ATT&CK Navigator Integration v14
DIMENSION A - Feature Expansion v14
Session 120 - June 23, 2026

ADD-ONLY MODULE - No existing code modified
100% backward compatible - wraps existing threat intelligence modules

Features:
1. MITRE ATT&CK Navigator Layer Generation
2. Tactic/technique heatmap visualization
3. Attack path traversal analysis
4. Coverage gap identification
5. Export to Navigator JSON format
6. Integration with existing MITRE mapper v13
"""

from typing import Dict, List, Optional, Tuple, Any
from dataclasses import dataclass, field
from enum import Enum
import json
import hashlib
from datetime import datetime


class MITREDomain(str, Enum):
    """MITRE ATT&CK domain enumeration"""
    ENTERPRISE = "enterprise-attack"
    MOBILE = "mobile-attack"
    ICS = "ics-attack"


class MITRETactic(str, Enum):
    """MITRE ATT&CK Enterprise tactics"""
    RECONNAISSANCE = "reconnaissance"
    RESOURCE_DEVELOPMENT = "resource-development"
    INITIAL_ACCESS = "initial-access"
    EXECUTION = "execution"
    PERSISTENCE = "persistence"
    PRIVILEGE_ESCALATION = "privilege-escalation"
    DEFENSE_EVASION = "defense-evasion"
    CREDENTIAL_ACCESS = "credential-access"
    DISCOVERY = "discovery"
    LATERAL_MOVEMENT = "lateral-movement"
    COLLECTION = "collection"
    COMMAND_AND_CONTROL = "command-and-control"
    EXFILTRATION = "exfiltration"
    IMPACT = "impact"


class ScoreColorMode(str, Enum):
    """Color scoring modes for Navigator"""
    DANGER_LEVEL = "danger-level"
    COVERAGE = "coverage"
    DETECTION_CONFIDENCE = "detection-confidence"
    OBSERVED_FREQUENCY = "observed-frequency"


@dataclass
class TechniqueScore:
    """Score entry for a single MITRE technique"""
    technique_id: str
    technique_name: str
    tactic: str
    score: float  # 0-100
    confidence: float = 0.0
    detected_count: int = 0
    last_detected: Optional[datetime] = None
    metadata: Dict[str, Any] = field(default_factory=dict)
    enabled: bool = True


@dataclass
class NavigatorLayerConfig:
    """Configuration for Navigator layer generation"""
    name: str
    domain: MITREDomain = MITREDomain.ENTERPRISE
    description: str = ""
    version: str = "4.6.1"
    color_mode: ScoreColorMode = ScoreColorMode.DANGER_LEVEL
    gradient_colors: Tuple[str, str, str] = ("#ffffff", "#ffd700", "#ff0000")
    show_tactic_row_borders: bool = True
    show_technique_subtechniques: bool = True
    legend_items: List[Dict[str, str]] = field(default_factory=list)


class MITREAttackNavigatorIntegrator:
    """
    MITRE ATT&CK Navigator Integration v14
    
    Generates compatible Navigator layer JSON for visualization
    of threat detection coverage, attack paths, and danger levels.
    
    Pure ADD-ONLY - integrates with existing MITRE mapper v13
    """
    
    TACTIC_ORDER = [
        "reconnaissance",
        "resource-development",
        "initial-access",
        "execution",
        "persistence",
        "privilege-escalation",
        "defense-evasion",
        "credential-access",
        "discovery",
        "lateral-movement",
        "collection",
        "command-and-control",
        "exfiltration",
        "impact"
    ]
    
    def __init__(self, config: Optional[NavigatorLayerConfig] = None):
        self.config = config or NavigatorLayerConfig(
            name="NeuralShield Threat Coverage",
            description="Auto-generated by NeuralShield Threat Intelligence v14"
        )
        self.techniques: Dict[str, TechniqueScore] = {}
        self._layer_cache: Optional[Dict[str, Any]] = None
    
    def register_technique(
        self,
        technique_id: str,
        technique_name: str,
        tactic: str,
        score: float,
        confidence: float = 0.0,
        detected_count: int = 0,
        metadata: Optional[Dict[str, Any]] = None
    ) -> None:
        """
        Register a MITRE technique with scoring
        
        Args:
            technique_id: MITRE technique ID (e.g., T1059)
            technique_name: Human-readable technique name
            tactic: Parent tactic name
            score: Score value 0-100
            confidence: Detection confidence 0-100
            detected_count: Number of times detected
            metadata: Additional metadata
        """
        score = max(0.0, min(100.0, score))
        confidence = max(0.0, min(100.0, confidence))
        
        self.techniques[technique_id] = TechniqueScore(
            technique_id=technique_id,
            technique_name=technique_name,
            tactic=tactic,
            score=score,
            confidence=confidence,
            detected_count=detected_count,
            last_detected=datetime.now() if detected_count > 0 else None,
            metadata=metadata or {}
        )
        self._layer_cache = None
    
    def register_from_threat_signature(
        self,
        signature_id: str,
        mitre_mappings: List[Dict[str, str]],
        threat_level: float
    ) -> None:
        """
        Register techniques from threat signature MITRE mappings
        
        Integration point with existing signature database v13
        
        Args:
            signature_id: Threat signature identifier
            mitre_mappings: List of {technique_id, tactic, name} dicts
            threat_level: Overall threat level 0-100
        """
        for mapping in mitre_mappings:
            technique_id = mapping.get("technique_id", "")
            if technique_id:
                self.register_technique(
                    technique_id=technique_id,
                    technique_name=mapping.get("name", technique_id),
                    tactic=mapping.get("tactic", "unknown"),
                    score=threat_level,
                    confidence=mapping.get("confidence", 50.0),
                    detected_count=1,
                    metadata={"signature_id": signature_id}
                )
    
    def batch_register_ioc_mitre_mappings(
        self,
        ioc_mitre_data: List[Dict[str, Any]]
    ) -> int:
        """
        Batch register MITRE mappings from IOC correlation results
        
        Integration point with IOC batch processor v13
        
        Args:
            ioc_mitre_data: List of IOC entries with mitre_techniques field
            
        Returns:
            Count of techniques registered
        """
        count = 0
        for ioc_entry in ioc_mitre_data:
            techniques = ioc_entry.get("mitre_techniques", [])
            threat_score = ioc_entry.get("threat_score", 50.0)
            for tech in techniques:
                self.register_technique(
                    technique_id=tech.get("id", ""),
                    technique_name=tech.get("name", ""),
                    tactic=tech.get("tactic", ""),
                    score=threat_score,
                    confidence=tech.get("confidence", 50.0),
                    detected_count=ioc_entry.get("occurrences", 1)
                )
                count += 1
        return count
    
    def calculate_coverage_gaps(self) -> Dict[str, List[str]]:
        """
        Identify tactics with technique coverage gaps
        
        Returns:
            Dictionary mapping tactics to list of uncovered technique IDs
        """
        # Standard enterprise techniques (abbreviated for this module)
        standard_techniques = {
            "initial-access": ["T1190", "T1566", "T1091", "T1200", "T1133"],
            "execution": ["T1059", "T1204", "T1053", "T1559", "T1072"],
            "persistence": ["T1547", "T1037", "T1546", "T1136", "T1084"],
            "privilege-escalation": ["T1548", "T1068", "T1547", "T1078", "T1037"],
            "defense-evasion": ["T1562", "T1070", "T1027", "T1564", "T1202"],
            "credential-access": ["T1555", "T1003", "T1556", "T1110", "T1557"],
            "discovery": ["T1087", "T1082", "T1016", "T1049", "T1033"],
            "lateral-movement": ["T1021", "T1550", "T1072", "T1091", "T1210"],
            "collection": ["T1114", "T1005", "T1115", "T1025", "T1113"],
            "command-and-control": ["T1071", "T1090", "T1573", "T1105", "T1571"],
            "exfiltration": ["T1041", "T1048", "T1020", "T1030", "T1567"],
            "impact": ["T1486", "T1490", "T1565", "T1489", "T1498"]
        }
        
        gaps = {}
        for tactic, expected_ids in standard_techniques.items():
            covered_ids = {
                t.technique_id 
                for t in self.techniques.values() 
                if t.tactic == tactic and t.score > 0
            }
            uncovered = [tid for tid in expected_ids if tid not in covered_ids]
            if uncovered:
                gaps[tactic] = uncovered
        
        return gaps
    
    def generate_attack_path(
        self,
        start_tactic: str = "initial-access",
        end_tactic: str = "impact",
        min_score: float = 30.0
    ) -> List[Dict[str, Any]]:
        """
        Generate probable attack path based on technique scores
        
        Args:
            start_tactic: Starting tactic in kill chain
            end_tactic: Ending tactic in kill chain
            min_score: Minimum score to include technique
            
        Returns:
            Ordered attack path with techniques
        """
        try:
            start_idx = self.TACTIC_ORDER.index(start_tactic)
            end_idx = self.TACTIC_ORDER.index(end_tactic)
        except ValueError:
            return []
        
        path = []
        for tactic in self.TACTIC_ORDER[start_idx:end_idx + 1]:
            tactic_techniques = [
                t for t in self.techniques.values()
                if t.tactic == tactic and t.score >= min_score
            ]
            
            if tactic_techniques:
                # Select highest scored technique for this tactic
                best = max(tactic_techniques, key=lambda x: x.score)
                path.append({
                    "tactic": tactic,
                    "technique_id": best.technique_id,
                    "technique_name": best.technique_name,
                    "score": best.score,
                    "confidence": best.confidence
                })
        
        return path
    
    def generate_navigator_layer(self) -> Dict[str, Any]:
        """
        Generate MITRE ATT&CK Navigator compatible layer JSON
        
        Returns:
            Navigator layer dictionary (can be JSON serialized)
        """
        if self._layer_cache is not None:
            return self._layer_cache
        
        techniques_list = []
        for tech in self.techniques.values():
            entry = {
                "techniqueID": tech.technique_id,
                "tactic": tech.tactic,
                "score": tech.score,
                "color": "",
                "comment": f"Confidence: {tech.confidence:.1f}% | Detections: {tech.detected_count}",
                "enabled": tech.enabled,
                "metadata": [
                    {"name": "Detection Confidence", "value": f"{tech.confidence:.1f}%"},
                    {"name": "Detection Count", "value": str(tech.detected_count)},
                    {"name": "Last Detected", "value": str(tech.last_detected) if tech.last_detected else "Never"}
                ] + [{"name": k, "value": str(v)} for k, v in tech.metadata.items()]
            }
            techniques_list.append(entry)
        
        layer = {
            "name": self.config.name,
            "versions": {
                "attack": "14",
                "navigator": "4.6.1",
                "layer": "4.4"
            },
            "domain": self.config.domain.value,
            "description": self.config.description,
            "filters": {
                "platforms": ["Windows", "macOS", "Linux", "Office 365", "Azure AD", "SaaS"]
            },
            "sorting": 0,
            "layout": {
                "layout": "side",
                "showID": False,
                "showName": True,
                "showAggregateScores": True,
                "countUnscored": False
            },
            "hideDisabled": False,
            "techniques": techniques_list,
            "gradient": {
                "colors": list(self.config.gradient_colors),
                "minValue": 0,
                "maxValue": 100
            },
            "legendItems": self.config.legend_items or [
                {"label": "Low Risk", "color": self.config.gradient_colors[0]},
                {"label": "Medium Risk", "color": self.config.gradient_colors[1]},
                {"label": "Critical Risk", "color": self.config.gradient_colors[2]}
            ],
            "showTacticRowBackground": self.config.show_tactic_row_borders,
            "tacticRowBackground": "#dddddd",
            "selectTechniquesAcrossTactics": True,
            "selectSubtechniquesWithParent": self.config.show_technique_subtechniques
        }
        
        self._layer_cache = layer
        return layer
    
    def export_navigator_json(self, filepath: Optional[str] = None) -> str:
        """
        Export Navigator layer to JSON string or file
        
        Args:
            filepath: Optional file path to write
            
        Returns:
            JSON string
        """
        layer = self.generate_navigator_layer()
        json_str = json.dumps(layer, indent=2)
        
        if filepath:
            with open(filepath, 'w') as f:
                f.write(json_str)
        
        return json_str
    
    def get_coverage_summary(self) -> Dict[str, Any]:
        """
        Get summary statistics of MITRE coverage
        
        Returns:
            Coverage summary dictionary
        """
        tactics_covered = set(t.tactic for t in self.techniques.values())
        scored_techniques = [t for t in self.techniques.values() if t.score > 0]
        
        by_tactic = {}
        for tactic in self.TACTIC_ORDER:
            tactic_techs = [t for t in self.techniques.values() if t.tactic == tactic]
            if tactic_techs:
                avg_score = sum(t.score for t in tactic_techs) / len(tactic_techs)
                by_tactic[tactic] = {
                    "technique_count": len(tactic_techs),
                    "average_score": round(avg_score, 2),
                    "detections_total": sum(t.detected_count for t in tactic_techs)
                }
        
        return {
            "total_techniques": len(self.techniques),
            "scored_techniques": len(scored_techniques),
            "tactics_covered": len(tactics_covered),
            "tactics_total": 14,
            "average_score": round(
                sum(t.score for t in scored_techniques) / len(scored_techniques)
                if scored_techniques else 0.0, 2
            ),
            "coverage_by_tactic": by_tactic,
            "gaps": self.calculate_coverage_gaps(),
            "layer_hash": hashlib.md5(
                json.dumps(self.generate_navigator_layer()).encode()
            ).hexdigest()[:8]
        }


# Module exports
__all__ = [
    "MITREDomain",
    "MITRETactic",
    "ScoreColorMode",
    "TechniqueScore",
    "NavigatorLayerConfig",
    "MITREAttackNavigatorIntegrator"
]
